In [5]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

In [6]:
plt.style.use("fivethirtyeight")

In [9]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # leraning rate
        self.epochs = epochs # iterations
    
    def fit(self, X, y):
        self.X = X
        self.y - y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X-with_bias}")

In [28]:
obj = Perceptron(eta=0.01, epochs=10)

In [29]:
obj.eta

0.01

In [30]:
obj.epochs

10

In [31]:
obj.weights

array([ 5.36948497e-05, -5.35746473e-05,  4.72528369e-05])

In [32]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
y = np.ones((4, 1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [35]:
obj.fit(X, y)

AttributeError: 'Perceptron' object has no attribute 'y'